import puppeteer from 'puppeteer-core';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const b=await puppeteer.launch({executablePath:CHROME,headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader']});
const p=await b.newPage();
await p.setViewport({width:1680,height:1050});
const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>m.type()==='error'&&errs.push(m.text()));
await p.goto('http://localhost:5174/',{waitUntil:'networkidle2'});
await new Promise(r=>setTimeout(r,700));
await p.evaluate(()=>{const kf=window.__kf; kf.doc.getState().removeObjects(kf.getActiveScene().objects.map(o=>o.id)); kf.doc.getState().setProjectName('Demo Animation');});
await (await p.$('input[accept*="stl"]')).uploadFile('/tmp/box.stl','/tmp/house.obj');
await new Promise(r=>setTimeout(r,1500));
await p.evaluate(()=>{[...document.querySelectorAll('button')].find(x=>x.textContent?.includes('Iso'))?.click();});
await new Promise(r=>setTimeout(r,600));
await p.evaluate(()=>{const kf=window.__kf; const id=kf.getActiveScene().objects[0].id; kf.editor.getState().setSelection([id]); kf.editor.getState().setPlayhead(0); kf.addKeyframeAtPlayhead(id); kf.editor.getState().setPlayhead(2500); kf.applyTransformEdit(id,{position:[450,0,250],rotation:[0,0,60],scale:[1,1,1]}); kf.editor.getState().setPlayhead(1200);});
await new Promise(r=>setTimeout(r,600));
await p.screenshot({path:'/tmp/kf-final.png'});
await b.close();
console.log(errs.length?('ERRORS: '+errs.join('; ')):'No errors. Final screenshot saved.');
